version: '3.5'

services:
    postgres:
        container_name: postgres_13
        image:  postgres:13.2
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        networks:
            - postgres_net
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_5
        image: dpage/pgadmin4:5.1
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-setme@pgadmin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5080}:80"
            - "${PGADMIN_HTTPS_PORT:-5443}:80"
        networks:
            - postgres_net
        restart: unless-stopped

networks:
    postgres_net:
        driver: bridge

volumes:
    postgres:
    pgadmin: