version: '3'
services:
  clickhouse:
    ports:
      - "8123:8123"
    image: yandex/clickhouse-server
    restart: unless-stopped
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
    clickhouse_data:
