version: "2"
services:
  server:
    image: redash/redash:latest
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    image: redash/redash:latest
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    image: redash/redash:latest
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    image: redash/redash:latest
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
    - "6379:6379"
  postgres:
    image: postgres:9.6-alpine
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      POSTGRES_PASSWORD: "password"
      REDASH_COOKIE_SECRET: "password"
      REDASH_SECRET_KEY: "password"
      REDASH_DATABASE_URL: "postgresql://postgres:password@postgres/postgres"
      #    env_file: /opt/redash/env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always

volumes:
  postgres-data: