version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
#    image: hpejak/nginx:1.0.1
    ports:
    - '80:80'
  web:
    image: httpd
    volumes:
    - ./html:/usr/local/apache2/htdocs/